#! /bin/sh

### BEGIN INIT INFO
# Provides:          cubian-firstrun
# Required-Start:    $remote_fs
# Required-Stop:
# Should-Start:
# Default-Start:     S   
# Default-Stop:
# Short-Description: Script to run when cubian first starting
# Description:       Something needs to be done when cubian is
#                    starting at first time.
#                      
#                    1. regenerate ssh host key
#                    2. regenerate ajenti private key
### END INIT INFO

N=/etc/init.d/cubian-firstrun

set -e

do_expand_rootfs(){
        device="/dev/mmcblk0"
        (echo d; echo n; echo p; echo 1; echo ; echo; echo w;) | fdisk $device 
return 0
}

case "$1" in
  start)
	    reboot=false
		echo "First run. This process takes around 1 minute to finish..." >> /dev/tty0
		echo "Expanding rootfs..." >> /dev/tty0
		if do_expand_rootfs;then
			echo "Expanding rootfs success, rebooting automatically..." >> /dev/tty0
			/sbin/insserv cubian-resize2fs
	    	reboot=true
		else
			echo "Expanding rootfs has failed, see log files." 
		fi
		set -e
		/sbin/insserv -r cubian-firstrun
		if $reboot;then
			/sbin/reboot
		fi
        ;;
  *)
        echo "Usage: $N {start}" >&2
        exit 1
        ;;
esac

exit 0
